# Generated by Django 3.0.8 on 2020-07-17 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import libi_common.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='수정 일시')),
                ('deleted_at', models.DateTimeField(db_index=True, help_text='삭제 일시', null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AreaGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='수정 일시')),
                ('deleted_at', models.DateTimeField(db_index=True, help_text='삭제 일시', null=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='수정 일시')),
                ('deleted_at', models.DateTimeField(db_index=True, help_text='삭제 일시', null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sharing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='수정 일시')),
                ('deleted_at', models.DateTimeField(db_index=True, help_text='삭제 일시', null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('goal_price', models.IntegerField()),
                ('sharing_type', models.IntegerField()),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libi_sharing.Area')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libi_sharing.Category')),
                ('created_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SharingPhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='수정 일시')),
                ('deleted_at', models.DateTimeField(db_index=True, help_text='삭제 일시', null=True)),
                ('file_name', models.CharField(help_text='첨부파일 이름', max_length=128, null=True)),
                ('file_ext', models.CharField(help_text='첨부파일 확장자', max_length=16, null=True)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='파일 크기', null=True)),
                ('file', models.ImageField(help_text='첨부이미지', null=True, upload_to=libi_common.utils.generate_upload_path)),
                ('sharing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libi_sharing.Sharing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SharingOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='수정 일시')),
                ('deleted_at', models.DateTimeField(db_index=True, help_text='삭제 일시', null=True)),
                ('description', models.CharField(max_length=16)),
                ('minimum_price', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('sharing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libi_sharing.Sharing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SharingApply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='수정 일시')),
                ('deleted_at', models.DateTimeField(db_index=True, help_text='삭제 일시', null=True)),
                ('apply_amount', models.IntegerField()),
                ('apply_price', models.IntegerField()),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sharing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libi_sharing.Sharing')),
                ('sharing_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libi_sharing.SharingOption')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='area',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libi_sharing.AreaGroup'),
        ),
    ]
