# Generated by Django 3.0.8 on 2020-07-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libi_sharing', '0003_auto_20200719_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharing',
            name='sharing_type',
            field=models.IntegerField(db_index=True),
        ),
    ]
