# Generated by Django 3.0.8 on 2020-07-17 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='수정 일시')),
                ('deleted_at', models.DateTimeField(db_index=True, help_text='삭제 일시', null=True)),
                ('phone', models.CharField(help_text='휴대전화번호', max_length=16, unique=True)),
                ('name', models.CharField(help_text='이름', max_length=64)),
                ('is_staff', models.BooleanField(default=False, help_text='관리자 여부')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='생성 일시')),
                ('refresh_token', models.CharField(help_text='RefreshToken', max_length=43, unique=True)),
                ('refreshed_time', models.DateTimeField(auto_now_add=True, help_text='토큰 갱신 일시')),
                ('expire_time', models.DateTimeField(help_text='토큰 만료 일시', null=True)),
                ('account', models.ForeignKey(help_text='토큰 발급 계정', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
